version: "3.9"

services:
  nextjs:
    build: .
    container_name: nextjs_app_
    ports:
      - "3002:3000"
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    env_file:
      - .env.local

volumes:
  node_modules:
